package id.sapikenal.app.report

import id.sapikenal.app.domain.model.ConsentStatus
import id.sapikenal.app.domain.model.DetectionResult
import id.sapikenal.app.domain.model.InferenceMode
import id.sapikenal.app.domain.model.LocationSource
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * Builds the text content for a detection report.
 * Pure function — no Android dependencies, fully testable.
 */
object ReportContentBuilder {
    data class ReportLabels(
        val title: String,
        val subtitle: String,
        val date: String,
        val predictedClass: String,
        val confidence: String,
        val reliable: String,
        val yes: String,
        val no: String,
        val inferenceMode: String,
        val online: String,
        val offline: String,
        val appVersion: String,
        val modelVersion: String,
        val preprocessing: String,
        val consentStatus: String,
        val allowed: String,
        val denied: String,
        val undecided: String,
        val coarseLocation: String,
        val gps: String,
        val manual: String,
        val detectionResult: String,
        val classScores: String,
        val technicalInformation: String,
        val device: String,
        val disclaimer: String,
        val notClinicalDiagnosis: String,
        val notOfficialDocument: String,
        val consultVeterinarian: String,
        val generatedBy: String,
        val classLabels: Map<String, String>,
    ) {
        fun classLabel(
            label: String,
            fallback: String,
        ): String = classLabels[label.lowercase(Locale.ROOT)] ?: fallback

        fun inferenceModeLabel(mode: InferenceMode): String = if (mode == InferenceMode.ONLINE) online else offline

        fun consentStatusLabel(status: ConsentStatus): String =
            when (status) {
                ConsentStatus.ALLOWED -> allowed
                ConsentStatus.DENIED -> denied
                ConsentStatus.UNDECIDED -> undecided
            }

        companion object {
            fun english() =
                ReportLabels(
                    title = "SapiKenal — Classification Report",
                    subtitle = "This is an image classification result from an AI model, not a clinical diagnosis.",
                    date = "Date",
                    predictedClass = "Predicted Class",
                    confidence = "Confidence",
                    reliable = "Reliable",
                    yes = "Yes",
                    no = "No",
                    inferenceMode = "Inference Mode",
                    online = "Online",
                    offline = "Offline",
                    appVersion = "App Version",
                    modelVersion = "Model Version",
                    preprocessing = "Preprocessing",
                    consentStatus = "Consent Status",
                    allowed = "Allowed",
                    denied = "Denied",
                    undecided = "Undecided",
                    coarseLocation = "Coarse Location",
                    gps = "GPS",
                    manual = "Manual",
                    detectionResult = "Detection Result",
                    classScores = "Class Scores",
                    technicalInformation = "Technical Information",
                    device = "Device",
                    disclaimer = "DISCLAIMER",
                    notClinicalDiagnosis = "This report contains an image classification result from an AI model (MobileNetV3).",
                    notOfficialDocument = "It is NOT a veterinary diagnosis, certificate, or official document.",
                    consultVeterinarian = "Consult a professional veterinarian for confirmation and treatment.",
                    generatedBy = "Generated by SapiKenal",
                    classLabels =
                        mapOf(
                            "fmd" to "FMD",
                            "healthy" to "Healthy",
                            "sehat" to "Healthy",
                            "lsd" to "LSD",
                        ),
                )
        }
    }

    data class ReportContent(
        val title: String,
        val subtitle: String,
        val resultLines: List<String>,
        val scoreLines: List<String>,
        val metadataLines: List<String>,
        val disclaimerLines: List<String>,
    )

    fun build(
        result: DetectionResult,
        appVersionName: String,
        labels: ReportLabels = ReportLabels.english(),
    ): ReportContent {
        val locale = Locale.getDefault()
        val dateStr = SimpleDateFormat("dd MMM yyyy, HH:mm", locale).format(Date(result.timestamp))
        val displayLabel = labels.classLabel(result.label, result.displayLabel)

        val resultLines =
            mutableListOf(
                "${labels.date}: $dateStr",
                "${labels.predictedClass}: $displayLabel",
                "${labels.confidence}: ${(result.confidence * 100).toInt()}%",
                "${labels.reliable}: ${if (result.isReliable) labels.yes else labels.no}",
                "${labels.inferenceMode}: ${labels.inferenceModeLabel(result.inferenceMode)}",
            )

        val scoreLines =
            result.allScores.entries
                .sortedByDescending { it.value }
                .map { (key, score) -> "${labels.classLabel(key, key)}: ${(score * 100).toInt()}%" }

        val metadataLines = mutableListOf<String>()
        result.appVersion?.let { metadataLines.add("${labels.appVersion}: $it") }
        result.modelVersion?.let { metadataLines.add("${labels.modelVersion}: $it") }
        result.preprocessingSummary?.let { metadataLines.add("${labels.preprocessing}: $it") }
        metadataLines.add("${labels.consentStatus}: ${labels.consentStatusLabel(result.consentStatus)}")
        if (result.latitude != null && result.longitude != null) {
            val sourceLabel =
                when (result.locationSource) {
                    LocationSource.GPS -> labels.gps
                    LocationSource.MANUAL -> labels.manual
                    else -> ""
                }
            val locText =
                "%.2f, %.2f".format(result.latitude, result.longitude) +
                    if (sourceLabel.isNotEmpty()) " ($sourceLabel)" else ""
            metadataLines.add("${labels.coarseLocation}: $locText")
        }

        val disclaimerLines =
            listOf(
                labels.notClinicalDiagnosis,
                labels.notOfficialDocument,
                labels.consultVeterinarian,
                "${labels.generatedBy} v$appVersionName",
            )

        return ReportContent(
            title = labels.title,
            subtitle = labels.subtitle,
            resultLines = resultLines,
            scoreLines = scoreLines,
            metadataLines = metadataLines,
            disclaimerLines = disclaimerLines,
        )
    }
}
