package id.sapikenal.app.report

import id.sapikenal.app.domain.model.BreedContract
import id.sapikenal.app.domain.model.ConsentStatus
import id.sapikenal.app.domain.model.DetectionResult
import id.sapikenal.app.domain.model.ImageSource
import id.sapikenal.app.domain.model.InferenceMode
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * Builds the text content for an identification report.
 * Pure function — no Android dependencies, fully testable.
 */
object ReportContentBuilder {
    data class ReportLabels(
        val title: String,
        val subtitle: String,
        val date: String,
        val predictedClass: String,
        val confidence: String,
        val inferenceMode: String,
        val online: String,
        val offline: String,
        val offlineFallback: String,
        val unknown: String,
        val appVersion: String,
        val processingTime: String,
        val preprocessing: String,
        val imageSource: String,
        val camera: String,
        val gallery: String,
        val recordTitle: String,
        val recordDescription: String,
        val consentStatus: String,
        val allowed: String,
        val denied: String,
        val undecided: String,
        val detectionResult: String,
        val classScores: String,
        val technicalInformation: String,
        val device: String,
        val disclaimer: String,
        val objectValidationLimitation: String,
        val identityDocumentLimitation: String,
        val supportedBreedsLimitation: String,
        val generatedBy: String,
        val classLabels: Map<String, String>,
    ) {
        fun classLabel(
            label: String,
            fallback: String,
        ): String = classLabels[label.lowercase(Locale.ROOT)] ?: fallback

        fun inferenceModeLabel(mode: InferenceMode): String =
            when (mode) {
                InferenceMode.ONLINE -> online
                InferenceMode.OFFLINE -> offline
                InferenceMode.OFFLINE_FALLBACK -> offlineFallback
                InferenceMode.UNKNOWN -> unknown
            }

        fun imageSourceLabel(source: ImageSource): String =
            when (source) {
                id.sapikenal.app.domain.model.ImageSource.CAMERA -> camera
                id.sapikenal.app.domain.model.ImageSource.GALLERY -> gallery
            }

        fun consentStatusLabel(status: ConsentStatus): String =
            when (status) {
                ConsentStatus.ALLOWED -> allowed
                ConsentStatus.DENIED -> denied
                ConsentStatus.UNDECIDED -> undecided
            }

        companion object {
            fun english() =
                ReportLabels(
                    title = "SapiKenal — Classification Report",
                    subtitle = "This is a cattle breed identification result from image classification.",
                    date = "Date",
                    predictedClass = "Predicted Class",
                    confidence = "Confidence",
                    inferenceMode = "Inference Mode",
                    online = "Online",
                    offline = "Offline",
                    offlineFallback = "Offline fallback",
                    unknown = "Unknown mode",
                    appVersion = "App Version",
                    processingTime = "Processing Time",
                    preprocessing = "Preprocessing",
                    imageSource = "Image Source",
                    camera = "Camera",
                    gallery = "Gallery",
                    recordTitle = "Title",
                    recordDescription = "Description",
                    consentStatus = "Consent Status",
                    allowed = "Allowed",
                    denied = "Denied",
                    undecided = "Undecided",
                    detectionResult = "Identification Result",
                    classScores = "Class Scores",
                    technicalInformation = "Technical Information",
                    device = "Device",
                    disclaimer = "DISCLAIMER",
                    objectValidationLimitation = "This report contains a cattle breed identification result from image classification, not validation that the image contains cattle.",
                    identityDocumentLimitation = "It is not proof of an individual animal identity or an official document.",
                    supportedBreedsLimitation = "This result is supporting information only; the app does not assess anything beyond the six supported breeds.",
                    generatedBy = "Generated by SapiKenal",
                    classLabels = BreedContract.DISPLAY_LABELS_EN,
                )
        }
    }

    data class ReportContent(
        val title: String,
        val subtitle: String,
        val resultLines: List<String>,
        val scoreLines: List<String>,
        val metadataLines: List<String>,
        val disclaimerLines: List<String>,
    )

    fun build(
        result: DetectionResult,
        appVersionName: String,
        labels: ReportLabels = ReportLabels.english(),
    ): ReportContent {
        require(result.confidence.isFinite() && result.confidence in 0f..1f) {
            "Invalid confidence"
        }
        val locale = Locale.getDefault()
        val dateStr = SimpleDateFormat("dd MMM yyyy, HH:mm", locale).format(Date(result.timestamp))
        val displayLabel = labels.classLabel(result.label, result.displayLabel)

        val resultLines =
            mutableListOf(
                "${labels.date}: $dateStr",
                "${labels.predictedClass}: $displayLabel",
                "${labels.confidence}: ${(result.confidence * 100).toInt()}%",
                "${labels.inferenceMode}: ${labels.inferenceModeLabel(result.inferenceMode)}",
            )

        val canonicalScores =
            BreedContract.CANONICAL_LABELS.map { key ->
                val score =
                    result.allScores[key]
                        ?: error("Missing canonical score for $key")
                require(score.isFinite() && score in 0f..1f) {
                    "Invalid canonical score for $key"
                }
                key to score
            }
        val scoreLines =
            canonicalScores
                .sortedByDescending { it.second }
                .map { (key, score) -> "${labels.classLabel(key, key)}: ${(score * 100).toInt()}%" }

        val metadataLines = mutableListOf<String>()
        result.appVersion?.let { metadataLines.add("${labels.appVersion}: $it") }
        result.processingMs?.let { metadataLines.add("${labels.processingTime}: $it ms") }
        result.preprocessingSummary?.let { metadataLines.add("${labels.preprocessing}: $it") }
        result.imageSource?.let { metadataLines.add("${labels.imageSource}: ${labels.imageSourceLabel(it)}") }
        result.title?.let { metadataLines.add("${labels.recordTitle}: $it") }
        result.description?.let { metadataLines.add("${labels.recordDescription}: $it") }
        metadataLines.add("${labels.consentStatus}: ${labels.consentStatusLabel(result.consentStatus)}")

        val disclaimerLines =
            listOf(
                labels.objectValidationLimitation,
                labels.identityDocumentLimitation,
                labels.supportedBreedsLimitation,
                "${labels.generatedBy} v$appVersionName",
            )

        return ReportContent(
            title = labels.title,
            subtitle = labels.subtitle,
            resultLines = resultLines,
            scoreLines = scoreLines,
            metadataLines = metadataLines,
            disclaimerLines = disclaimerLines,
        )
    }
}
